var GC_APPEARANCE = {
	'weekdays':  ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'], 
	'longmonth' : ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Deciembre'],
	'messages' : {
				'Warning' : 'Warning: the date entered does not meet preset date format',
				'AltPrevYear' : 'to previos year',
				'AltNextYear' : 'to next year',
				'AltPrevMonth' : 'to previos month',
				'AltNextMonth' : 'to next month'
	},
	'CalDiv' : 'clsCalDiv',
	'OuterFrame' : 'clsOuterFrame',
	'InnerFrame' : 'clsInnerFrame',
	'TopPartNavpanel' : 'clsTopPartNavpanel',
	'BottomPartNavpanel' : 'clsBottomPartNavpanel',
	'MidRow' : 'clsMidRow',
	'DateGrid':'clsDateGrid',
	'WeekDay':'clsWeekDay',
	'WorkDayCell': 'clsWorkDayCell',
	'HoliDayCell': 'clsHoliDayCell',
	'OtherMonthDayCell': 'clsOtherMonthDayCell',
	'SelectedDayCell': 'clsSelectedDayCell',
	'CurrentMonthDay': 'clsCurrentMonthDay',
	'OtherMonthDay': 'clsOtherMonthDay',
	'SelectedDay': 'clsSelectedDay',
	'InfoTitle':'clsInfoTitle',
	'DataArea':'clsDataArea',
	'PrevYear':'../pop_Calendar/img/prev_year.gif',
	'PrevMonth':'../pop_Calendar/img/prev_month.gif',
	'NextYear':'../pop_Calendar/img/next_year.gif',
	'NextMonth':'../pop_Calendar/img/next_month.gif',
	'IcoCalUnVis': '../pop_Calendar/img/dpr_unvis.gif',
	'IcoCalVis': '../pop_Calendar/img/dpr_vis.gif'

};